reset;

option solver gurobi;
option gurobi_options 'timelimit=600';

model "models/regularised/model.mod";
data  "experiments/exp_01_synthetic_baseline/outputs/data.dat";
update data NT , c_grid;
data  "experiments/exp_03_uk_validation/uk_grid_data/uk_mip_apx_hourly_168h_2026-02-15_to_2026-02-21.dat";

solve;

printf "\n---- EXP03 REGULARISED SUMMARY ----\n";
printf "Status    = %s\n", solve_result;
printf "TotalCost = %.6f\n", TotalCost;
printf "gamma_on  = %.6f\n", gamma_on;
printf "beta_on   = %.6f\n", beta_on;
printf "gamma_Pb  = %.6f\n", gamma_Pb;

printf "Writing results_regularised_uk.txt ...\n";

# Columns:
# [t  price Pgrid Pg Pc Pd SoC Pb gen_state gen_start u_c u_d]
printf {t in T}
"%d %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %d %d\n",
t,
load[t],
c_grid[t],
Pgrid[t],
Pg[t],
Pc[t],
Pd[t],
SoC[t],
Pb[t],
s_g[t],      # relaxed generator state
ds_abs[t],   # switching surrogate
0, 0
> "experiments/exp_03_uk_validation/outputs/results_regularised_uk.txt";

printf "Done.\n";

# include "models/regularised/run_exp03.run";