reset;

option solver gurobi;
option gurobi_options 'timelimit=600';

model "models/convex/model.mod";
data  "experiments/exp_01_synthetic_baseline/outputs/data.dat";
update data NT , c_grid;
data  "experiments/exp_03_uk_validation/uk_grid_data/uk_mip_apx_hourly_168h_2026-02-15_to_2026-02-21.dat";

solve;

printf "\n---- EXP03 CONVEX SUMMARY ----\n";
printf "Status    = %s\n", solve_result;
printf "TotalCost = %.6f\n", TotalCost;

printf "Writing results_convex_uk.txt ...\n";

# Columns:
# [t  price Pgrid Pg Pc Pd SoC Pb gen_state gen_start u_c u_d]
printf {t in T}
"%d %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %.6f %d %d\n",
t,
load[t],
c_grid[t],
Pgrid[t],
Pg[t],
Pc[t],
Pd[t],
SoC[t],
(Pd[t]-Pc[t]),
0,      # gen_state (unused in convex)
0,      # gen_start (unused in convex)
0, 0
> "experiments/exp_03_uk_validation/outputs/results_convex_uk.txt";

printf "Done.\n";

#include "models/convex/run_exp03.run";